version: "3"
services:
  app:
    container_name: meetbook-api
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ~/meetbook-api:/app
      - ~/meetbook-api/node_modules:/app/node_modules
    ports:
      - 8000:8000
    networks:
      - web_network

  nginx:
    container_name: meetbook-api-nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
    networks:
      - web_network
    depends_on:
      - app

networks:
  web_network:
    driver: bridge
